# This workflow will build, test, and create a binary for a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  create-binary:
    needs: build-and-test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create application bundle
      run: |
        chmod +x ./build.sh
        ./build.sh
    - name: Create ZIP archive
      run: |
        zip -r WNBASchedule.zip WNBASchedule.app
    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: WNBASchedule
        path: WNBASchedule.zip
        retention-days: 7  # Artifacts will be available for 7 days before being automatically deleted
